environment:
  PYTHON_VERSION: 3.6
  PYTHON_ARCH: 64
  PYTHON: "C:\\Python36-x64"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

  matrix:
    - TOXENV: py36

pull_requests:
  do_not_increment_build_number: true

install:
  # If there is a newer build queued for same PR, cancel this one. Credit: JuliaLang devs
  - ps:
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
      throw "There are newer queued builds for this pull request, failing early." }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -VV"
  - if defined TOXENV (
    python -m pip install tox tox_venv
    ) else (
    python -m pip install -rrequirements.txt pygame bbfreeze pefile
    )
  - "SET PATH=C:\\OpenSSL-v11-Win64\\bin;%PATH%"
  - openssl version -v
  - python -m pip install deluge-libtorrent
  - 'python -c "import libtorrent; print(libtorrent.__version__)"'

cache:
  - '%LOCALAPPDATA%\pip\cache'

build: false

test_script:
  - if defined TOXENV tox
# Commented out as require GTK3 to create package.
# after_test:
# - if not defined TOXENV python setup.py build && python setup.py install
# - cd %APPVEYOR_BUILD_FOLDER%\\packaging\\win32
# - if not defined TOXENV deluge-bbfreeze.py debug
# - "SET PATH=C:\\Program Files (x86)\\NSIS;%PATH%"
# - if not defined TOXENV makensis deluge-win32-installer.nsi
# - if not defined TOXENV 7z a deluge-win32.zip build-win32 "-x!*.exe"

# artifacts:
# - path: packaging\win32\deluge-win32.zip
# - path: packaging\win32\build-win32\*.exe

#on_success:
#
